# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 17:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='project',
        ),
        migrations.AddField(
            model_name='project',
            name='image',
            field=models.FileField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Images',
        ),
    ]
