# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-03 23:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_auto_20170903_2058'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='picture',
        ),
    ]
