# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 11:06
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('contact_number', models.PositiveIntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('date', models.DateTimeField(default=datetime.datetime(2017, 8, 29, 11, 6, 12, 622413, tzinfo=utc))),
                ('enquiry', models.TextField()),
            ],
        ),
    ]
